# Generated by Django 3.2.16 on 2022-10-19 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('key', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('target_url', models.URLField(max_length=1024)),
                ('secret_key', models.CharField(max_length=16, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitedURL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_pc', models.BooleanField()),
                ('user_ip', models.GenericIPAddressField()),
                ('viewed_date', models.DateTimeField(auto_now_add=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.url')),
            ],
        ),
    ]
