# Generated by Django 3.2.16 on 2022-10-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URL',
            new_name='URLMapping',
        ),
    ]
