# Generated by Django 3.2.16 on 2022-10-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_url_urlmapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitedurl',
            old_name='viewed_date',
            new_name='visited_date',
        ),
    ]
